[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Kara Babcock", email = "kara@tachyondecay.net"},
]
dependencies = [
    "arrow==0.17.0",
    "bcrypt==3.2.0",
    "beautifulsoup4==4.9.3",
    "diff-match-patch==20200713",
    "email-validator==1.1.2",
    "flask==1.1.2",
    "flask-login==0.5.0",
    "flask-sqlalchemy==2.4.4",
    "flask-wtf==0.14.3",
    "gunicorn==20.0.4",
    "itsdangerous==1.1.0",
    "jinja2==2.11.2",
    "markdown==3.3.3",
    "markupsafe==1.1.1",
    "passlib==1.7.4",
    "python-slugify==4.0.1",
    "sqlalchemy==1.3.22",
    "sqlalchemy-utils==0.36.8",
    "werkzeug==1.0.1",
    "whoosh==2.7.4",
    "wtforms==2.3.3",
    "wtforms-alchemy==0.17.0",
    "wtforms-components==0.10.4",
    "python-dotenv~=0.19",
]
requires-python = ">=3.8"
dynamic = ["classifiers"]
license = {text = "N/A"}

[project.urls]
homepage = ""


[project.optional-dependencies]
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"


[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "coverage==5.3.1",
    "factory-boy==3.1.0",
    "pytest==6.2.1"]

[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
