[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Kara Babcock", email = "kara@tachyondecay.net"},
]
dependencies = [
    "arrow~=1.1",
    "bcrypt~=3.2",
    "beautifulsoup4~=4.9",
    "diff-match-patch~=20200713.0",
    "email-validator~=1.1",
    "flask~=2.0",
    "flask-login~=0.5",
    "flask-sqlalchemy~=2.5",
    "flask-wtf~=0.15",
    "gunicorn~=20.1",
    "itsdangerous~=2.0",
    "jinja2~=3.0",
    "markdown~=3.3",
    "markupsafe~=2.0",
    "passlib~=1.7",
    "python-slugify~=5.0",
    "sqlalchemy~=1.4",
    "sqlalchemy-utils~=0.37",
    "werkzeug~=2.0",
    "whoosh~=2.7",
    "wtforms~=2.3",
    "wtforms-alchemy~=0.17",
    "wtforms-components~=0.10",
    "python-dotenv~=0.19",
    "psycopg2-binary~=2.9",
    "flask-migrate~=3.1",
]
requires-python = ">=3.8"
dynamic = ["classifiers"]
license = {text = "N/A"}

[project.urls]
homepage = ""


[project.optional-dependencies]
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"


[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "coverage~=5.5",
    "factory-boy~=3.2",
    "pytest~=6.2",
    "pylint~=2.9",
]

[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
