"""Add List and ListItem models.

Revision ID: 7b3bba6081ed
Revises: 8f1b897458b7
Create Date: 2021-08-16 22:28:18.088298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3bba6081ed'
down_revision = '8f1b897458b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reverse_order', sa.Boolean(), nullable=True),
    sa.Column('show_numbers', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['posts.id'], name=op.f('fk_lists_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lists'))
    )
    op.create_table('list_items',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('blurb', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name=op.f('fk_list_items_list_id_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_list_items_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'post_id', name=op.f('pk_list_items'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_items')
    op.drop_table('lists')
    # ### end Alembic commands ###
