# This is a basic workflow to help you get started with Actions

name: 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: mirror-repository
      # You may pin to the exact commit or the version.
      # uses: spyoungtech/mirror-action@b313a53232e77d8f7d8fcdb00f90b94100767be1
      uses: spyoungtech/mirror-action@v0.4.3
      with:
        # The remote repository e.g. https://github.com/octocat/foo.git or git@github.com:octocat/foo.git
        REMOTE: git@github.com:tachyondecay/tachyondecay.net-mirror.git
        # The ssh private key for writing to the remote repository, if using ssh
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
        GIT_SSH_NO_VERIFY_HOST: "true"
